name: Deploy Frontend to Azure ACI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. sprint1, sprint2)'
        required: true
        default: 'test'

env:
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  ACR_NAME:      ${{ vars.ACR_NAME }}
  ACR_SERVER:    ${{ vars.ACR_SERVER }}
  IMAGE_NAME:    frontend
  BACKEND_URL:  ${{vars.BACKEND_URL}}
  TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ACR_SERVER }}
        username: ${{ env.ACR_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
        build-args: |
          REACT_APP_API_URL=http://${{ env.BACKEND_URL }}

    - name: Delete existing Frontend ACI (if any)
      run: |
        az container delete \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name plantandgo-frontend \
          --yes || echo "No existing frontend to delete"

    - name: Deploy Frontend to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name plantandgo-frontend \
          --image ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }} \
          --cpu 1 \
          --memory 1 \
          --registry-login-server ${{ env.ACR_SERVER }} \
          --registry-username ${{ env.ACR_NAME }} \
          --registry-password "${{ secrets.ACR_PASSWORD }}" \
          --dns-name-label plantandgo-frontend \
          --ip-address public \
          --os-type Linux \
          --ports 80
