name: Run Tests with Vitest

on:
  push:
    branches: [master] # Run tests on pushes to the master branch
  pull_request:
    branches: [master] # Run tests on pull requests to the master branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests with Vitest
      - name: Run tests
        run: npx vitest
